sitegroup: dcco

deploy_tasks:
  development:
    before_deploy:
      - composer install
    after_deploy:
      - cd web && drush cim -y
      - cd web && drush updb --cache-clear=0 -y
      - cd web && drush cr -y
  production:
    before_deploy:
      - composer install
    after_deploy:
      - cd web && drush updb --cache-clear=0 -y
      - cd web && drush cr -y

shared:
  production:
    - src: files
      dst: web/sites/default/files
