<?php

/**
 * @file
 * Main module file.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function dcco_sponsors_preprocess_taxonomy_term(&$variables) {
  $element = $variables['elements'];
  $entity = $element['#taxonomy_term'];

  // Taxonomy terms don't pull in tagged content by default. Add that here for
  // sponsorship level terms.
  if ($entity->bundle() == 'sponsor_tiers') {
    $sponsors = Drupal::service('entity.query')
      ->get('node')
      ->condition('type', 'sponsor')
      ->condition('field_sponsor_tier', $entity->id())
      ->condition('status', 1)
      ->execute();

    if (!empty($sponsors)) {
      $variables['sponsors'] = [
        '#type' => 'view',
        '#name' => 'sponsor_listings',
        '#display_id' => 'embed_1',
        '#arguments' => [$entity->id()],
        '#embed' => TRUE,
      ];
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function dcco_sponsors_preprocess_node(&$variables) {
  $node = $variables['node'];
  $view_mode = $variables['elements']['#view_mode'];
  $current_user = \Drupal::currentUser();

  if (
    $node->bundle() == 'sponsor' &&
    $view_mode == 'full' &&
    $node->hasField('field_sponsor_tier') &&
    !$current_user->hasPermission('bypass node access')
  ) {
    // Get sponsor levels, see if sponsor is of Bronze level.
    $sponsor_ids = array_map(function ($item) {
      return $item['target_id'];
    }, $node->get('field_sponsor_tier')->getValue());

    if (in_array('3', $sponsor_ids)) {
      $redirect = new RedirectResponse(\Drupal::url('entity.node.canonical', [
        'node' => 2,
      ]));
      $redirect->setStatusCode(403)->send();
    }
  }
}
